FROM python:3.13-slim-trixie AS builder

ARG QUANTIZATION

LABEL org.opencontainers.image.authors="Eryk Mikołajewicz <eryk.mikolajewicz@gmail.com>" \
      org.opencontainers.image.version=1 \
      org.opencontainers.image.description="Deployment of gemma 300m embedding model with onnx." \
      org.opencontainers.image.source="https://github.com/ErykMikolajewicz/prawobiorca-backend" \
      quantization=${QUANTIZATION} \
      maintainer="Eryk Mikołajewicz"

WORKDIR /embedding_deployment

RUN pip install --no-cache-dir uv

COPY pyproject.toml pyproject.toml

RUN uv sync --no-dev

COPY onnx_build.py onnx_build.py

RUN ./.venv/bin/python onnx_build.py --quantization ${QUANTIZATION}


FROM python:3.13-slim-trixie

RUN useradd -r embedding_generator

USER embedding_generator

WORKDIR /embedding_deployment

COPY --from=builder /embedding_deployment/onnx onnx
COPY --from=builder /embedding_deployment/.venv .venv

COPY src src

EXPOSE 8000

ENV PATH="/embedding_deployment/.venv/bin:$PATH"

ENTRYPOINT ["uvicorn", "--port", "8000", "--host", "0.0.0.0", "src.main:app"]