FROM python:3.13-slim-trixie AS builder

ARG QUANTIZATION

LABEL quantization=${QUANTIZATION}

WORKDIR /embedding_deployment

RUN pip install --no-cache-dir uv

COPY pyproject.toml pyproject.toml

RUN uv sync --group sentence-transformers --no-cache

# RUN useradd -r embedding_generator

# RUN chown -R embedding_generator:embedding_generator /embedding_deployment

# USER embedding_generator

COPY building/sentence-transformers/sentence_transformers_build.py sentence_transformers_build.py
RUN --mount=type=secret,id=hf_token .venv/bin/python sentence_transformers_build.py

COPY src src

EXPOSE 8000

ENV PATH="/embedding_deployment/.venv/bin:$PATH"

ENV DECODER_TYPE=SENTENCE_TRANSFORMERS

ENTRYPOINT ["uvicorn", "--port", "8000", "--host", "0.0.0.0", "src.main:app"]