FROM python:3.13-slim-trixie AS builder

ARG QUANTIZATION

WORKDIR /embedding_deployment

RUN pip install --no-cache-dir uv

COPY pyproject.toml pyproject.toml

RUN uv sync --group onnx-build --no-cache

COPY building/onnx/model_download.py model_download.py

RUN .venv/bin/python model_download.py --quantization ${QUANTIZATION}

RUN uv sync --group onnx-runtime --no-cache

FROM python:3.13-slim-trixie

ARG QUANTIZATION

LABEL quantization=${QUANTIZATION}

ENV APP_DECODER_TYPE=ONNX
ENV ENVIRONMENT=CONTAINER

RUN useradd -r embedding_generator

USER embedding_generator

WORKDIR /embedding_deployment

COPY --from=builder /embedding_deployment/onnx onnx
COPY --from=builder /embedding_deployment/.venv .venv

COPY src src

EXPOSE 8000

ENV PATH="/embedding_deployment/.venv/bin:$PATH"

ENTRYPOINT ["uvicorn", "--port", "8000", "--host", "0.0.0.0", "src.main:app"]