FROM python:3.13-slim-trixie AS builder

ENV APP_DECODER_TYPE=SENTENCE_TRANSFORMERS
ENV ENVIRONMENT=CONTAINER

RUN useradd -r embedding_generator

RUN pip install --no-cache-dir uv

WORKDIR /embedding_deployment

RUN chown embedding_generator:embedding_generator /embedding_deployment
USER embedding_generator

COPY pyproject.toml pyproject.toml

RUN uv sync --group sentence-transformers --no-cache

COPY building/sentence_transformers/model_download.py model_download.py

USER root
RUN --mount=type=secret,id=hf_token .venv/bin/python model_download.py
USER embedding_generator

COPY src src

EXPOSE 8000

ENV PATH="/embedding_deployment/.venv/bin:$PATH"

ENTRYPOINT ["uvicorn", "--port", "8000", "--host", "0.0.0.0", "src.main:app"]