FROM python:3.13-slim-trixie AS builder

ARG QUANTIZATION

LABEL quantization=${QUANTIZATION}

RUN useradd -r embedding_generator

WORKDIR /embedding_deployment

RUN pip install --no-cache-dir uv

COPY pyproject.toml pyproject.toml

RUN uv sync --group sentence-transformers --no-cache

COPY building/sentence_transformers/sentence_transformers_build.py sentence_transformers_build.py
RUN --mount=type=secret,id=hf_token .venv/bin/python sentence_transformers_build.py --quantization ${QUANTIZATION}

RUN chown -R embedding_generator:embedding_generator /embedding_deployment
USER embedding_generator

COPY src src

EXPOSE 8000

ENV PATH="/embedding_deployment/.venv/bin:$PATH"

ENV APP_DECODER_TYPE=SENTENCE_TRANSFORMERS
ENV APP_ENVIRONMENT=CONTAINER

ENTRYPOINT ["uvicorn", "--port", "8000", "--host", "0.0.0.0", "src.main:app"]