FROM docker.io/ollama/ollama:latest

ARG QUANTIZATION

LABEL quantization=${QUANTIZATION}

ENV OLLAMA_HOST=0.0.0.0:11434
ENV OLLAMA_ORIGINS=*

RUN ollama serve & \
    sleep 10 && \
    ollama pull embeddinggemma:300m${QUANTIZATION}

EXPOSE 11434
